version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: controlepecas-sql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "ControlePecas@2025"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - controlepecas-sql-data:/var/opt/mssql

volumes:
  controlepecas-sql-data:
